export default {
  ONBOARDING: {
    WELCOME_TITLE: 'WELCOME',
    THANKS_COMMENT:
      'Welcome to Hacker News Feed App! We are thrilled to have you here. Explore our features, personalize your experience, and make the most of what we offer. If you need help, just reach out José Duarte. Enjoy your journey!',
    SELECT_INTEREST_FACETS: 'We would like to know a little more about you.',
    OMIT: 'Discard onboarding',
    CONTINUE: 'CONTINUE',
    PREFERENCE:
      'In order to personalize your experience we are going to show you some topics that might interest you.',
  },
  HOME: {
    NUMBER_SKELETON: 7,
    STORAGE_KEY: 'StorageKeys::STORAGE_SAVED_DATA',
  },
  USER_ACTIVITY: {
    RECONSIDER_PUSH_NOTIFICATIONS_PERMISSION_TITLE:
      'We’ve got news updates waiting for you!',
    RECONSIDER_PUSH_NOTIFICATIONS_PERMISSION:
      'Missed something important? Customize your notifications to only receive updates on topics you care about. Would you like to turn them back on?',
    STORAGE_KEY: 'StorageKeys::USER_ACTIVITY_HACKER_NEWS_SAVED_DATA',
    FACETS: {
      keywords: {
        general: [
          'Best',
          'Top',
          'How to',
          'Guide',
          'Reviews',
          'Tips',
          'Cheap',
          'Deals',
          'Near me',
          'Free',
        ],
        technology: [
          'Latest',
          'Download',
          'Update',
          'Tutorial',
          'Software',
          'App',
          'Device',
          'Comparison',
          'Features',
          'Security',
        ],
        health_and_wellness: [
          'Symptoms',
          'Benefits',
          'Diet',
          'Exercise',
          'Mental health',
          'Wellness',
          'Nutrition',
          'Remedies',
          'Recipes',
          'Fitness',
        ],
        travel: [
          'Destinations',
          'Flights',
          'Hotels',
          'Packages',
          'Itinerary',
          'Travel tips',
          'Tours',
          'Attractions',
          'Reviews',
          'Local experiences',
        ],
        shopping: [
          'Discount',
          'Sales',
          'Coupons',
          'Compare prices',
          'Best sellers',
          'New arrivals',
          'Brands',
          'Gifts',
          'Fashion',
          'Electronics',
        ],
        education: [
          'Courses',
          'Online classes',
          'Study tips',
          'Scholarships',
          'Degree',
          'Certification',
          'Resources',
          'Tutorials',
          'Learning',
          'Subjects',
        ],
      },
    },
  },
};
